---

- name: "Build application GazellaCOM"
  ansible.builtin.include_tasks: build.yml
  when: gazella_mode == 'build'    

- name: "Prepare application to tranfer"
  ansible.builtin.include_tasks: transfer_prepare.yml
  when: gazella_mode == 'build'    

- name: "Tranfer Compress package"
  ansible.builtin.include_tasks: transfer_push.yml
  when: gazella_mode == 'deploy'    

- name: "Deploy new package on wildfly"
  ansible.builtin.include_tasks: deploy.yml
  when: gazella_mode == 'deploy'    
