---
- name: "Preoare to Password Update"
  block:

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Ensure app workdir exists: {{ gazella_encode_workdir }}"
      become: yes
      ansible.builtin.file:
        path: "{{ gazella_local_workdir }}"
        state: directory
        owner: "{{ gazella_awx_user }}"
        group: "{{ gazella_awx_group }}"
        mode: 0775
        force: yes

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Encode directory workdir exists: {{ gazella_local_workdir }}/lib"
      become_user: "{{ gazella_awx_user }}"
      ansible.builtin.file:
        path: "{{ gazella_local_workdir }}/lib"
        state: directory
        owner: "{{ gazella_awx_user }}"
        group: "{{ gazella_awx_group }}"
        mode: 0775
        force: yes

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Encode directory workdir exists: {{ gazella_local_workdir }}/bin"
      become_user: "{{ gazella_awx_user }}"
      ansible.builtin.file:
        path: "{{ gazella_local_workdir }}/bin"
        state: directory
        owner: "{{ gazella_awx_user }}"
        group: "{{ gazella_awx_group }}"
        mode: 0775
        force: yes

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Encode directory workdir exists: {{ gazella_local_workdir }}/update_password"
      become_user: "{{ gazella_awx_user }}"
      ansible.builtin.file:
        path: "{{ gazella_local_workdir }}/update_password"
        state: directory
        owner: "{{ gazella_awx_user }}"
        group: "{{ gazella_awx_group }}"
        mode: 0775
        force: yes

    - name: Install - Copy the commons-codec.jar  
      ansible.builtin.copy: 
        src: commons-codec.jar 
        dest: "{{ gazella_local_workdir }}/lib/commons-codec.jar"
        owner: "{{ gazella_awx_user }}" 
        group: "{{ gazella_awx_group }}" 
        force: no 
        mode: 0775    

    - name: Install - Copy the jboss-logging.jar  
      ansible.builtin.copy: 
        src: jboss-logging.jar 
        dest: "{{ gazella_local_workdir }}/lib/jboss-logging.jar"
        owner: "{{ gazella_awx_user }}" 
        group: "{{ gazella_awx_group }}" 
        force: no 
        mode: 0775    

    - name: Install - Copy the RunEncode.class  
      ansible.builtin.copy: 
        src: RunEncode.class
        dest: "{{ gazella_local_workdir }}/bin/RunEncode.class"
        owner: "{{ gazella_awx_user }}" 
        group: "{{ gazella_awx_group }}" 
        force: no 
        mode: 0775    

    - name: Install - Copy the Encode.class  
      ansible.builtin.copy: 
        src: Encode.class
        dest: "{{ gazella_local_workdir }}/bin/Encode.class"
        owner: "{{ gazella_awx_user }}" 
        group: "{{ gazella_awx_group }}" 
        force: no 
        mode: 0775    

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Create encode file from commom-encode on file {{ gazella_local_workdir }}/update_password/update_password-{{ my_date }}-{{ my_time }}.output "
      become_user: "{{ gazella_awx_user }}"
      ansible.builtin.shell: "java -cp .:{{ gazella_local_workdir }}/lib/commons-codec.jar:{{ gazella_local_workdir }}/lib/jboss-logging.jar RunEncode  {{ gazella_update_password }} > {{ gazella_local_workdir }}/update_password/update_password-{{ my_date }}-{{ my_time }}.output"
      args:
        chdir: "{{ gazella_local_workdir }}/bin"

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Read file update_password-{{ my_date }}-{{ my_time }}.output "
      ansible.builtin.command: "cat {{ gazella_local_workdir }}/update_password/update_password-{{ my_date }}-{{ my_time }}.output"
      ignore_errors: true
      changed_when: false
      register: gazella_update_password_read
      become: yes

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Set global variable gazella_update_password= {{ gazella_update_password_read.stdout }} "
      ansible.builtin.set_fact:
        gazella_update_password: "{{ gazella_update_password_read.stdout }}"

    - name: "AWX BUILD SERVER - PREPARE UPDATE PASSWORD - Copy sql for update password" 
      ansible.builtin.template: 
        src: gazella-update-password.sql.j2
        dest: "{{ gazella_local_workdir }}/update_password/update_password-{{ my_date }}-{{ my_time }}.sql"
        owner: "{{ gazella_awx_user }}" 
        group: "{{ gazella_awx_group }}" 
        force: no 
        mode: 0775    

