---

- name: "Build app from {{ gazella_build_repo_url }} on '{{ gazella_builder_repo_branch }}'."
  block:

    - name: "AWX BUILD SERVER - Ensure app sequences exists: {{ gazella_build_sequence }}"
      ansible.builtin.file:
        path: "{{ gazella_build_sequence }}"
        state: directory
        owner: "{{ gazella_build_user }}"
        group: "{{ gazella_build_group }}"
        mode: 0775
        force: yes

    - name: "AWX BUILD SERVER - Touch if dont exist {{ gazella_build_sequence_file }}"
      ansible.builtin.file:
        path: "{{ gazella_build_sequence_file }}"
        state: touch
        mode: u+rw,g-wx,o-rwx
        modification_time: preserve
        access_time: preserve

    - name: AWX BUILD SERVER - Print message if ansible version is greater than 2.7.0
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "AWX BUILD SERVER - Read file and put variable from {{ gazella_build_sequence_file }} "
      ansible.builtin.command: "cat {{ gazella_build_sequence_file }}"
      ignore_errors: true
      changed_when: false
      register: gazella_number_build_read
      become: yes

    - name: "AWX BUILD SERVER - Set global variable gazella_number_build"
      ansible.builtin.set_fact:
        gazella_number_build: "{{ gazella_number_build_read.stdout }}"

    - name: "AWX BUILD SERVER - Increment variable gazella_number_build = {{ gazella_number_build | int + 1 }}"
      ansible.builtin.set_fact: 
        gazella_number_build={{ gazella_number_build | int + 1 }}

    - name: "AWX BUILD SERVER - set sequence file {{ gazella_build_sequence_file }} to {{ gazella_number_build }}"
      ansible.builtin.shell: "echo {{ gazella_number_build }} > {{ gazella_build_sequence_file }}"

    - name: "AWX BUILD SERVER - Delete previous workdir {{ gazella_build_workdir }}."
      ansible.builtin.file:
        path: "{{ gazella_build_workdir }}"
        state: absent

    - name: "AWX BUILD SERVER - Ensure app workdir exists: {{ gazella_build_workdir }}"
      ansible.builtin.file:
        path: "{{ gazella_build_workdir }}"
        state: directory
        owner: "{{ gazella_build_user }}"
        group: "{{ gazella_build_group }}"
        mode: 0775
        force: yes

    - name: "AWX BUILD SERVER - Bitbucket Checkout the application source code Gazella COM"
      ansible.builtin.git:
        repo: "{{ gazella_build_repo_url }}"
        dest: "{{ gazella_build_workdir }}"
        version: "{{ gazella_build_repo_branch }}"
      ignore_errors: yes  

    - name: "AWX BUILD SERVER - Bitbucket Recursively change ownership"
      become: yes
      file:
        path: "{{ gazella_build_workdir}}"
        state: directory
        recurse: yes
        owner: "{{ gazella_build_user }}"
        group: "{{ gazella_build_group }}"

    - name: "AWX BUILD SERVER - Git fix trusted directory"
      ansible.builtin.command: "git config --global --add safe.directory {{ gazella_build_workdir }}"
      args:
        chdir: "{{ gazella_build_workdir }}"

    - name: "AWX BUILD SERVER - Build the App using Maven"
      ansible.builtin.command: "mvn -X -s customer/{{ gazella_build_profile_customer }}/settings.xml clean package -Dbuild.number={{ gazella_number_build }} -P{{ gazella_build_profile_environment }}"
      register: mvn_build
      environment:
        JAVA_HOME: "{{ gazella_java_home }}"
      args:
        chdir: "{{ gazella_build_workdir }}"
      changed_when: false

    - name: "AWX BUILD SERVER - Display build application log"
      ansible.builtin.debug:
        var: mvn_build.stdout
#      when:
#        - display_mvn_output is defined
