---
#- name: "Delete previous workdir (if requested)."
#  ansible.builtin.file:
#    path: /opt/demoansible3
#    state: directory

- name: "Build applicationo GazellaCOM"
  ansible.builtin.include_tasks: build.yml
  when: gazellacom_mode == 'build'    

- name: "Prepare application to tranfer"
  ansible.builtin.include_tasks: transfer_prepare.yml
  when: gazellacom_mode == 'build'    

- name: "Tranfer Compress package"
  ansible.builtin.include_tasks: transfer_push.yml
  when: gazellacom_mode == 'deploy'    

- name: "Deploy new package on wildfly"
  ansible.builtin.include_tasks: deploy.yml
  when: gazellacom_mode == 'deploy'    
