---
  
- name: "{{ gazella_project|upper }} {{ gazella_environment|upper }} SERVER DEPLOY - Deploy application as a systemd service on target system."
  become: yes
  ansible.builtin.shell: bash /opt/jboss/bin/jboss-cli.sh --connect --command="undeploy *.war" || true
    
- name: "{{ gazella_project|upper }} {{ gazella_environment|upper }} SERVER DEPLOY - Stop service wildfly"
  become: yes
  ansible.builtin.systemd_service:
    state: stopped
    name: wildfly

- name: "{{ gazella_project|upper }} {{ gazella_environment|upper }} SERVER DEPLOY - Remove all termporal files from wildfly."
  become: yes
  ansible.builtin.shell: rm -rf /opt/jboss/standalone/tmp

- name: "{{ gazella_project|upper }} {{ gazella_environment|upper }} SERVER DEPLOY - Start service wildfly"
  become: yes
  ansible.builtin.systemd_service:
    state: started
    name: wildfly

