---
  
- name: "{{ gazella_project|upper }} {{ gazella_app|upper }} {{ gazella_environment|upper }} RESTART SERVER - Deploy application as a systemd service on target system."
  become: yes
  ansible.builtin.shell: bash /opt/jboss/bin/jboss-cli.sh --connect --command="undeploy *.war" || true
    
- name: "{{ gazella_project|upper }} {{ gazella_app|upper }} {{ gazella_environment|upper }} RESTART SERVER - Stop service wildfly"
  become: yes
  ansible.builtin.systemd_service:
    state: stopped
    name: wildfly

- name: "{{ gazella_project|upper }} {{ gazella_app|upper }} {{ gazella_environment|upper }} RESTART SERVER - Remove all undeploy file from wildfly."
  become: yes
  ansible.builtin.shell: rm -rf /opt/jboss/standalone/deployments/*.undeployed      

- name: "{{ gazella_project|upper }} {{ gazella_app|upper }} {{ gazella_environment|upper }} RESTART SERVER - Remove all termporal files from wildfly."
  become: yes
  ansible.builtin.shell: rm -rf /opt/jboss/standalone/tmp

- name: "{{ gazella_project|upper }} {{ gazella_app|upper }} {{ gazella_environment|upper }} RESTART SERVER - Start service wildfly"
  become: yes
  ansible.builtin.systemd_service:
    state: started
    name: wildfly

